export const USER_AUTHENTICATION = 'USER_AUTHENTICATION';
export const REGISTER_USER = 'REGISTER_USER';
export const USER_LOGOUT = 'USER_LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_ERROR_CLEAR = 'AUTH_ERROR_CLEAR';
export const DELETE_VACCINE = 'DELETE_VACCINE';
export const ADD_VACCINE = 'ADD_VACCINE';
export const UPDATE_USER_PLAN = 'UPDATE_USER_PLAN';

